### ISSUE TITLE
Gem breaks with rails 7.1

### ISSUE THREAD

**Issue by skatkov** [cheddar-me/pbbuilder#24]
## Description
This gem breaks for rails HEAD version (e.g. 7.1), instead of usual hash structure, we're getting string representation of a hash structure.

Issue was discovered in this PR https://github.com/cheddar-me/pbbuilder/pull/19

## Steps
- Uncomment testing against "rails_head"
- Run `appraisal install`
- Run `appraisal rake`

## Result
Following errors are returned for tests that run against rails head.
```
Error:
PbbuilderTemplateTest#test_nested_message_partial:
NoMethodError: undefined method `best_friend' for "<API::Person: name: \"Chris Harris\", friends: [], best_friend: <API::Person: name: \"Max Verstappen\", friends: [], nicknames: [], favourite_foods: {}>, nicknames: [], favourite_foods: {}>":String

    assert_equal "Max Verstappen", result.best_friend.name
                                         ^^^^^^^^^^^^
    /Users/skatkov/Code/pbbuilder/test/pbbuilder_template_test.rb:77:in `block in <class:PbbuilderTemplateTest>'
```

```
Error:
PbbuilderTemplateTest#test_basic_template:
NoMethodError: undefined method `name' for "<API::Person: name: \"hello\", friends: [], nicknames: [], favourite_foods: {}>":String

    assert_equal "hello", result.name
                                ^^^^^
    /Users/skatkov/Code/pbbuilder/test/pbbuilder_template_test.rb:26:in `block in <class:PbbuilderTemplateTest>'
```

## Expected result
Instead of a hash structure returned as it was before, now string representation of hash is being returned.

**Comment by julik** [comment]
It looks like we are not alone - the ActionView API has changed and it converts rendered data into strings

https://github.com/rails/rails/issues/50930

In a way this would be an interesting excercise (a proto message is a string of bytes after all) but at what cost?

**Comment by julik** [comment]
And this got fixed upstream in https://github.com/rails/rails/pull/51023 @skatkov can you check whether it works again?
